services:
  db:
    build: .                                   # CHANGED: Build from local Dockerfile
    # image: postgres:17.7                     # REMOVED: Replaced by build
    container_name: fansipan-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ADDED: Load pg_cron and configure it to run in your specific DB
    command: ["postgres", "-c", "shared_preload_libraries=pg_cron", "-c", "cron.database_name=${POSTGRES_DB}"]
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
