services:
  db:
    image: postgres:17.7
    container_name: fansipan-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          # Reads from .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Reads from .env
      POSTGRES_DB: ${POSTGRES_DB}              # Reads from .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
